### ISSUE TITLE
DANG COMPILE  ERROR

### ISSUE THREAD

**Issue by Nefomemes** [BLThunderstorm/BLThunderstorm#114]
**Describe the bug**
Got this when compiling pages.

```
ERROR  in ./pages/_game/user/_username/index.vue?vue&type=template&id=388b36eb&              friendly-errors 07:28:26

Syntax Error: Unexpected token (1:375)                                                      friendly-errors 07:28:26

                                                                                              friendly-errors 07:28:26
 @ ./pages/_game/user/_username/index.vue?vue&type=template&id=388b36eb& 1:0-288 1:0-288
 @ ./pages/_game/user/_username/index.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/eventsource-polyfill/dist/browserify-eventsource.js ./node_modules/webpack-hot-middleware/client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js
 ```
**To Reproduce**

Run Nuxt.js development server 

**Expected behavior**
No errors.
**Screenshots**

**Additional context**
```
ERROR in ./pages/_game/user/_username/index.vue?vue&type=template&id=388b36eb& (../node_modules/.pnpm/vue-loader@15.9.7_559ffc97fd41de05d12663d7fb949156/node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./pages/_game/user/_username/index.vue?vue&type=template&id=388b36eb&)
Module build failed (from ../node_modules/.pnpm/vue-loader@15.9.7_559ffc97fd41de05d12663d7fb949156/node_modules/vue-loader/lib/loaders/templateLoader.js):
SyntaxError: Unexpected token (1:375)
    at Parser.pp$4.raise (/mnt/d/Projects/BLThunderstorm/node_modules/.pnpm/vue-template-es2015-compiler@1.9.1/node_modules/vue-template-es2015-compiler/buble.js:2757:13)
    at Parser.pp.unexpected (/mnt/d/Projects/BLThunderstorm/node_modules/.pnpm/vue-template-es2015-compiler@1.9.1/node_modules/vue-template-es2015-compiler/buble.js:647:8)
    at Parser.pp$3.parseExprAtom (/mnt/d/Projects/BLThunderstorm/node_modules/.pnpm/vue-template-es2015-compiler@1.9.1/node_modules/vue-template-es2015-compiler/buble.js:2196:10)
    at Parser.<anonymous> (/mnt/d/Projects/BLThunderstorm/node_modules/.pnpm/vue-template-es2015-compiler@1.9.1/node_modules/vue-template-es2015-compiler/buble.js:6003:24)
    at Parser.parseExprAtom (/mnt/d/Projects/BLThunderstorm/node_modules/.pnpm/vue-template-es2015-compiler@1.9.1/node_modules/vue-template-es2015-compiler/buble.js:6129:31)
    at Parser.pp$3.parseExprSubscripts (/mnt/d/Projects/BLThunderstorm/node_modules/.pnpm/vue-template-es2015-compiler@1.9.1/node_modules/vue-template-es2015-compiler/buble.js:2047:19)
    at Parser.pp$3.parseMaybeUnary (/mnt/d/Projects/BLThunderstorm/node_modules/.pnpm/vue-template-es2015-compiler@1.9.1/node_modules/vue-template-es2015-compiler/buble.js:2024:17)
    at Parser.pp$3.parseExprOps (/mnt/d/Projects/BLThunderstorm/node_modules/.pnpm/vue-template-es2015-compiler@1.9.1/node_modules/vue-template-es2015-compiler/buble.js:1966:19)
    at Parser.pp$3.parseMaybeConditional (/mnt/d/Projects/BLThunderstorm/node_modules/.pnpm/vue-template-es2015-compiler@1.9.1/node_modules/vue-template-es2015-compiler/buble.js:1949:19)
    at Parser.pp$3.parseMaybeAssign (/mnt/d/Projects/BLThunderstorm/node_modules/.pnpm/vue-template-es2015-compiler@1.9.1/node_modules/vue-template-es2015-compiler/buble.js:1925:19)
    at Parser.pp$3.parseMaybeConditional (/mnt/d/Projects/BLThunderstorm/node_modules/.pnpm/vue-template-es2015-compiler@1.9.1/node_modules/vue-template-es2015-compiler/buble.js:1954:28)
    at Parser.pp$3.parseMaybeAssign (/mnt/d/Projects/BLThunderstorm/node_modules/.pnpm/vue-template-es2015-compiler@1.9.1/node_modules/vue-template-es2015-compiler/buble.js:1925:19)
    at Parser.pp$3.parseExprList (/mnt/d/Projects/BLThunderstorm/node_modules/.pnpm/vue-template-es2015-compiler@1.9.1/node_modules/vue-template-es2015-compiler/buble.js:2663:20)
    at Parser.pp$3.parseSubscripts (/mnt/d/Projects/BLThunderstorm/node_modules/.pnpm/vue-template-es2015-compiler@1.9.1/node_modules/vue-template-es2015-compiler/buble.js:2075:29)
    at Parser.pp$3.parseExprSubscripts (/mnt/d/Projects/BLThunderstorm/node_modules/.pnpm/vue-template-es2015-compiler@1.9.1/node_modules/vue-template-es2015-compiler/buble.js:2050:21)
    at Parser.pp$3.parseMaybeUnary (/mnt/d/Projects/BLThunderstorm/node_modules/.pnpm/vue-template-es2015-compiler@1.9.1/node_modules/vue-template-es2015-compiler/buble.js:2024:17)
    at Parser.pp$3.parseExprOp (/mnt/d/Projects/BLThunderstorm/node_modules/.pnpm/vue-template-es2015-compiler@1.9.1/node_modules/vue-template-es2015-compiler/buble.js:1985:41)
    at Parser.pp$3.parseExprOps (/mnt/d/Projects/BLThunderstorm/node_modules/.pnpm/vue-template-es2015-compiler@1.9.1/node_modules/vue-template-es2015-compiler/buble.js:1968:91)
    at Parser.pp$3.parseMaybeConditional (/mnt/d/Projects/BLThunderstorm/node_modules/.pnpm/vue-template-es2015-compiler@1.9.1/node_modules/vue-template-es2015-compiler/buble.js:1949:19)
    at Parser.pp$3.parseMaybeAssign (/mnt/d/Projects/BLThunderstorm/node_modules/.pnpm/vue-template-es2015-compiler@1.9.1/node_modules/vue-template-es2015-compiler/buble.js:1925:19)
    at Parser.pp$3.parseExprList (/mnt/d/Projects/BLThunderstorm/node_modules/.pnpm/vue-template-es2015-compiler@1.9.1/node_modules/vue-template-es2015-compiler/buble.js:2663:20)
    at Parser.pp$3.parseSubscripts (/mnt/d/Projects/BLThunderstorm/node_modules/.pnpm/vue-template-es2015-compiler@1.9.1/node_modules/vue-template-es2015-compiler/buble.js:2075:29)
```
    

There's no CODE written in the error telling what went wrong. DANG IT.

If this keeps happening, I would have to start this project from the start using another framework.

**Comment by Nefomemes** [comment]
We are migrating to Next.js
